version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/index
      - /index/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "423:80"  # Nginx varsayılan olarak 80 portunu kullanır, bu yüzden hostun 423 portunu container'ın 80 portuna yönlendir
    volumes:
      - ./frontend/src:/app/src
      - ./node_modules:/src/app/node_modules
